name: Build & test

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    outputs:
      any-changed: ${{ github.event_name == 'workflow_dispatch' || steps.filter.outputs.dotnet == 'true' || steps.filter.outputs.ts == 'true' }}
      dotnet-changed: ${{ github.event_name == 'workflow_dispatch' || steps.filter.outputs.dotnet == 'true' }}
      ts-changed: ${{ github.event_name == 'workflow_dispatch' || steps.filter.outputs.ts == 'true' }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: 🔎 checking for changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            dotnet:
              - 'src/Spillgebees.Blazor.RichTextEditor/**'
              - 'src/Spillgebees.Blazor.RichTextEditor.Tests/**'
              - 'src/Spillgebees.Blazor.RichTextEditor.Samples/**'
              - 'src/Directory.Packages.props'
              - 'src/General.targets'
              - 'src/.editorconfig'
              - 'global.json'
              - 'Spillgebees.Blazor.RichTextEditor.slnx'
              - 'Directory.Solution.targets'
              - '.config/**'
              - '.github/workflows/**'
            ts:
              - 'src/Spillgebees.Blazor.RichTextEditor.Assets/**'
              - '.github/workflows/**'

  build-and-test:
    name: build-and-test
    permissions:
      contents: write
    needs: changes
    uses: ./.github/workflows/build-test-publish.yml
    with:
      should-run: ${{ needs.changes.outputs.any-changed == 'true' }}
      dotnet-changed: ${{ needs.changes.outputs.dotnet-changed == 'true' }}
      ts-changed: ${{ needs.changes.outputs.ts-changed == 'true' }}
      should-publish-gh-page: ${{ github.event_name == 'push' && needs.changes.outputs.any-changed == 'true' }}
      gh-page-destination-directory: main
