name: Build, test, & publish

permissions: {}

on:
  workflow_call:
    inputs:
      should-package:
        type: boolean
        description: Whether to package project and upload as artifact.
        default: false
      should-run:
        type: boolean
        description: Whether to run the job.
        default: true
      dotnet-changed:
        type: boolean
        description: Whether .NET source files changed.
        default: true
      ts-changed:
        type: boolean
        description: Whether TypeScript source files changed.
        default: true

jobs:
  build-test-publish:
    name: build-test-publish
    if: inputs.should-run
    runs-on: ubuntu-latest
    env:
      HUSKY: 0

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 📦 setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          package_json_file: src/Spillgebees.Blazor.RichTextEditor.Assets/package.json

      - name: 📦 setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: src/Spillgebees.Blazor.RichTextEditor.Assets/pnpm-lock.yaml

      - name: 📦 setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
          global-json-file: global.json

      - name: 📦 restore packages
        run: dotnet restore Spillgebees.Blazor.RichTextEditor.slnx

      - name: 👷 build project
        run: dotnet build --configuration Release --no-restore Spillgebees.Blazor.RichTextEditor.slnx

      - name: 🔍 lint TypeScript
        if: inputs.ts-changed
        run: pnpm run lint
        working-directory: src/Spillgebees.Blazor.RichTextEditor.Assets

      - name: ✅ test .NET
        if: inputs.dotnet-changed
        run: dotnet test --solution Spillgebees.Blazor.RichTextEditor.slnx --configuration Release --no-build

      - name: ✅ test TypeScript
        if: inputs.ts-changed
        run: pnpm run test
        working-directory: src/Spillgebees.Blazor.RichTextEditor.Assets

      - name: 📦 package the application
        if: inputs.should-package
        run: dotnet pack src/Spillgebees.Blazor.RichTextEditor/Spillgebees.Blazor.RichTextEditor.csproj --configuration Release --no-build --output package

      - name: 🔃 upload artifacts
        if: inputs.should-package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifacts
          if-no-files-found: error
          retention-days: 1
          path: package/*.nupkg
