name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: Spillgebees/Blazor.Docs.Sdk/.github/workflows/deploy-docs.yml@1b0a4ebf31bdb43946587bda0a37a778f3d2f441 # main
    with:
      docs-project-path: src/Spillgebees.Blazor.RichTextEditor.Docs/Spillgebees.Blazor.RichTextEditor.Docs.csproj
      base-href: /Blazor.RichTextEditor/
