name: Publish nuget package

permissions: {}

on:
  release:
    types: [published]

jobs:
  build-and-test:
    name: build-and-test
    uses: ./.github/workflows/build-test-publish.yml
    permissions:
      contents: write
    with:
      should-package: true
      should-publish-gh-page: true
      gh-page-destination-directory: ${{ github.event.release.tag_name }}

  publish:
    name: publish
    needs: [build-and-test]
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: 🔃 download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: artifacts
          path: .

      - name: 📦 setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5

      - name: 🚀 publish nuget packages
        run: dotnet nuget push "*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
