name: Publish nuget package

permissions: {}

on:
  release:
    types: [published]

jobs:
  build-and-test:
    name: build-and-test
    uses: ./.github/workflows/build-test-publish.yml
    with:
      should-package: true

  publish:
    name: publish
    needs: [build-and-test]
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: 🔃 download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: artifacts
          path: .

      - name: 📦 setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5

      - name: 🚀 publish nuget packages
        run: dotnet nuget push "*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
