name: Workflow security analysis

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zizmor:
    name: zizmor
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: Spillgebees/admin/.github/workflows/zizmor.yml@f6c22b8407c830b3a1a9c2f42a771068f23fc333 # main
