name: Workflow security analysis

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zizmor:
    name: zizmor
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: Spillgebees/admin/.github/workflows/zizmor.yml@71ebb6702e4b0a9085eb83fe1bf1431a3c08903a # main
