name: Workflow security analysis

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zizmor:
    name: zizmor
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: Spillgebees/admin/.github/workflows/zizmor.yml@e75cced477868f4707780f3a664b73f262994a49 # main
